apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} #mongodb
  labels:
    app: database
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }} #27017
      nodePort:  {{ .Values.service.nodeport }} #30005
  selector:
    app: database
